server:
  port: 8086

spring:
  application:
    name: notification-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://host.docker.internal:3307/notifications_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: UTKARSH@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.LinkedHashMap

eureka:
  client:
    service-url:
      defaultZone: http://quickbite-eureka:8761/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always