version: '3.8'

services:

  # ===== INFRASTRUCTURE =====

  mysql:
    image: mysql:8.0
    container_name: quickbite-mysql
    environment:
      MYSQL_ROOT_PASSWORD: UTKARSH@123
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quickbite-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: quickbite-redis-compose
    ports:
      - "6379:6379"
    networks:
      - quickbite-network

  zookeeper:
    image: zookeeper:3.8
    container_name: quickbite-zookeeper-compose
    ports:
      - "2181:2181"
    networks:
      - quickbite-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: quickbite-kafka-compose
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - quickbite-network

  mongodb:
    image: mongo:7
    container_name: quickbite-mongodb-compose
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - quickbite-network

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: quickbite-elasticsearch-compose
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - quickbite-network

  # ===== SPRING BOOT SERVICES =====

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - quickbite-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider",
             "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - eureka-server
      - redis
    networks:
      - quickbite-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=UTKARSH@123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      - mysql
      - eureka-server
    networks:
      - quickbite-network

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restaurant_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=UTKARSH@123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      - mysql
      - redis
      - kafka
      - eureka-server
    networks:
      - quickbite-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orders_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=UTKARSH@123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      - mysql
      - redis
      - kafka
      - eureka-server
    networks:
      - quickbite-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payments_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=UTKARSH@123
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      - mysql
      - kafka
      - eureka-server
    networks:
      - quickbite-network

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/delivery_db?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - kafka
      - eureka-server
    networks:
      - quickbite-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notifications_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=UTKARSH@123
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      - mysql
      - kafka
      - eureka-server
    networks:
      - quickbite-network

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - elasticsearch
      - kafka
      - eureka-server
    networks:
      - quickbite-network

networks:
  quickbite-network:
    driver: bridge

volumes:
  mysql_data: