server:
  port: 8087

spring:
  application:
    name: search-service

  threads:
    virtual:
      enabled: true

  elasticsearch:
    uris: http://quickbite-elasticsearch:9200   

  kafka:
    bootstrap-servers: quickbite-kafka:9092   
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.LinkedHashMap

eureka:
  client:
    service-url:
      defaultZone: http://quickbite-eureka:8761/eureka/   # 🔥 FIXED

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always